# Generated by Django 3.0.1 on 2019-12-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file',
            new_name='song_file',
        ),
    ]
